# Generated by Django 2.1.2 on 2018-12-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Selenium Project', 'Selenium Project'), ('Dummy Project', 'Dummy Project')], max_length=40)),
            ],
        ),
    ]
