# Generated by Django 2.0.9 on 2019-01-25 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_gui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runtest',
            name='run_id',
        ),
    ]
