# Generated by Django 2.1.2 on 2018-12-29 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_gui', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='RunTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=60)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_gui.Run')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='test',
            name='project_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_gui.Project'),
        ),
        migrations.AddField(
            model_name='test',
            name='running_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='runtest',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_gui.Test'),
        ),
    ]
