# Generated by Django 2.0.9 on 2019-01-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_gui', '0003_auto_20181229_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='full_name',
            field=models.TextField(default=False, max_length=150),
        ),
    ]
