# Generated by Django 2.0.9 on 2019-01-25 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_gui', '0004_remove_runtest_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtest',
            name='end_time',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='runtest',
            name='logs',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='runtest',
            name='result',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='runtest',
            name='run_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_gui.Run'),
        ),
        migrations.AddField(
            model_name='runtest',
            name='start_time',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='runtest',
            name='test_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_gui.Test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='full_name',
            field=models.TextField(default=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.TextField(default=None),
        ),
    ]
